---

- hosts: all
  become: true
  tasks:

    # This will update apt repo cache and then install apache2 package. This will try to avoid stale apt cache    
  - name: install apache and php packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"  
      state: latest
      update_cache: yes  

