---

- hosts: all
  become: true
  tasks:

    # This will update apt repo cache and then install apache2 package. This will try to avoid stale apt cache    
  - name: update repository index
    apt:
      update_cache: yes  
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

    # This section will update repo cache then install apache for AlmaLinux
  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"

  - name: install apache package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "AlmaLinux"
