---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (AlmaLinux)
    dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"
  
  - name: install updates (Ubuntu)
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 

- hosts: web_servers
  become: true
  tasks:

    # This will update apt repo cache and then install apache2 package. This will try to avoid stale apt cache
  - name: install apache2 and php packages
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

    # This section will update repo cache then install apache for AlmaLinux
  - name: install apache and php packages
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "AlmaLinux"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (AlmaLinux)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "AlmaLinux"

  - name: install mariadb package (Ubuntu)
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package: 
      name: samba
      state: latest
